[variables]
FORCE_REBUILD = '2025-07-15-backend-complete'

[phases.setup]
nixPkgs = [
  '(python311Full.withPackages (ps: with ps; [pip setuptools wheel flask flask-cors gunicorn pillow numpy flask-sqlalchemy psycopg2 flask-login werkzeug email-validator pyjwt requests flask-dance oauthlib sqlalchemy]))'
]
aptPkgs = ['libgl1', 'libglib2.0-0']

[phases.build]
dependsOn = ['setup']
cmds = ['echo "Complete backend Python environment ready with safe imports"']

[start]
cmd = 'gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 120 app:app'
