[variables]
FORCE_REBUILD = '2025-07-15-pip-fix'

[phases.setup]
nixPkgs = ['python311', 'python311Packages.pip', 'python311Packages.setuptools', 'python311Packages.wheel']
aptPkgs = ['libgl1', 'libglib2.0-0']

[phases.install]
dependsOn = ['setup']
cmds = ['pip install --upgrade pip setuptools wheel']

[phases.build]
dependsOn = ['install']
cmds = ['pip install -r requirements_deploy.txt']

[start]
cmd = 'gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 120 app:app'
