[variables]
FORCE_REBUILD = '2025-07-15-streamlined'

[phases.setup]
nixPkgs = ['python311Full']
aptPkgs = ['libgl1', 'libglib2.0-0']

[phases.install]
dependsOn = ['setup']
cmds = [
  'pip install --no-cache-dir --disable-pip-version-check Flask==3.1.1',
  'pip install --no-cache-dir --disable-pip-version-check flask-cors==6.0.1',
  'pip install --no-cache-dir --disable-pip-version-check gunicorn==23.0.0',
  'pip install --no-cache-dir --disable-pip-version-check flask-sqlalchemy==3.1.1',
  'pip install --no-cache-dir --disable-pip-version-check psycopg2-binary==2.9.10'
]

[start]
cmd = 'gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 120 app:app'
