[variables]
FORCE_REBUILD = '2025-07-15-nixonly'

[phases.setup]
nixPkgs = [
  '(python311Full.withPackages (ps: with ps; [flask flask-cors gunicorn flask-sqlalchemy psycopg2 flask-login werkzeug]))'
]
aptPkgs = ['libgl1', 'libglib2.0-0']

[phases.build]
dependsOn = ['setup']
cmds = ['echo "Python environment ready"']

[start]
cmd = 'gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 120 app:app'
