[phases.setup]
nixPkgs = ['libGL', 'libGLU', 'glib', 'libxcrypt-legacy', 'mesa', 'xorg.libX11', 'xorg.libXext', 'xorg.libXrender']

[phases.install]
cmds = ['pip install --upgrade pip']

[start]
cmd = 'gunicorn --bind 0.0.0.0:$PORT main:app'